/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.notify.conf
 */
#ifndef PETHNOTIFICATIONS_H
#define PETHNOTIFICATIONS_H

/* function declarations */
int send_pethPsePortOnOffNotification_trap(int grpid, int portid, int status);
int send_pethMainPowerUsageOnNotification_trap(void);
int send_pethMainPowerUsageOffNotification_trap(void);

#endif /* PETHNOTIFICATIONS_H */
