/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.old-api.conf
 */
#ifndef POWERETHERNETMIB_H
#define POWERETHERNETMIB_H

#define MAX_TYPE_VAL_LEN    8

/* function declarations */
void init_powerEthernetMIB(void);
FindVarMethod var_powerEthernetMIB;
FindVarMethod var_pethPsePortTable;
FindVarMethod var_pethMainPseTable;
FindVarMethod var_pethNotificationControlTable;
    WriteMethod write_pethPsePortAdminEnable;
    WriteMethod write_pethPsePortPowerPairs;
    WriteMethod write_pethPsePortPowerPriority;
    WriteMethod write_pethPsePortType;
    WriteMethod write_pethMainPseUsageThreshold;
    WriteMethod write_pethNotificationControlEnable;

#endif /* POWERETHERNETMIB_H */
