/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.notify.conf
 */
#ifndef FILETRAP_H
#define FILETRAP_H

/* function declarations */
int send_fileChange_trap(char *name, int status);

#endif /* FILETRAP_H */
